### ISSUE TITLE
Source controller marked class files throw System.UnauthorizedAccessException during SourceMap

### ISSUE THREAD

**Issue by shamveelcoder** [gasparnagy/SpecFlow.xUnitAdapter#16]
Whenever the feature file associated to source control which automaticaally marks file attribute as readOnly. Now during SourceMap when the build task try to write sourceMap content to file it fails with below exception - 

   _at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.AppendAllLines(String path, IEnumerable`1 contents)
   at SpecFlow.xUnitAdapter.Build.SpecFlowSourceMapAppender.AppendSourceMap(ITaskItem item)
   at SpecFlow.xUnitAdapter.Build.SpecFlowSourceMapAppender.Execute()_

It's good idea to remove Readonly attribute before we write clone copy of feature file .

**Comment by gasparnagy** [comment]
Fixed (will be included in v1.2 releasing today). Please note that once this will be released, you have to delete your `obj` folder once to remove all remaining read-only feature files from it.
